version: "2"
services:
  ingest:
    container_name: ingest
    restart: always
    build: .
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - /mongo_data:/data/db
    ports:
      - "27017:27017"
