version: "2"
services:
  ingest:
    container_name: ingest
    restart: always
    build: .
    volumes:
      - /etc/cert:/etc/cert
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: --sslMode requireSSL --sslPEMKeyFile /etc/cert/mongo.keypem.pem --sslCAFile /etc/cert/ca.crt
    restart: always
    volumes:
      - /etc/cert:/etc/cert
      - /mongo_data:/data/db
    ports:
      - "27017:27017"
